version: '3'

services:
  cassandra:
    image: cassandra:4.0
    ports:
      - 9042:9042
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cluster-main
  nifi:
    image: apache/nifi:latest
    ports:
      - 8080:8080 # Unsecured HTTP Web Port
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=false
      - NIFI_ELECTION_MAX_WAIT=30 sec
    volumes:
            # - nifi-conf:/opt/nifi/nifi-current/conf
      - ./scripts:/opt/nifi/nifi-current/scripts
      - ./data_transfer:/opt/nifi/nifi-current/data_transfer

volumes:
  cassandra-data:
  nifi-conf:
