version: '3'

services:
  cassandra:
    image: bitnami/cassandra:4.0
    ports:
      - '7001:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra

  nifi:
    image: apache/nifi:latest
    ports:
      - 8080 # Unsecured HTTP Web Port
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ELECTION_MAX_WAIT=1 min
    volumes:
      - nifi-conf:/opt/nifi/nifi-current/conf
      - ./scripts:/scripts/

volumes:
  cassandra_data:
  nifi-conf:
